import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { motion } from 'framer-motion'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Animation />
    </>
  )
}

const Animation = () => {

  return (
    <div>
      <div className={styles.header1}>
        <h3>Did you find what you are looking for?</h3>
      </div>
        <h5 className={styles.phone}>Hotline: +95 987654321</h5>
      <div>
        <motion.div className={styles.meterior}
            animate={{
              y: [ 0, 20, 0 ],
              borderRadius: ["0%", "0%", "50%", "50%", "0%"]
            }}
            transition={{
              duration: 2,
              repeat: Infinity,
            }}
        >
          <Image src='./images/bottom right small meterior.svg' width={110} height={110} />
        </motion.div>
        <div className={styles.flyingMeterior}>
          <Image src='./images/flyingMeterior.svg' width={200} height={200} />
        </div>
        <div className={styles.meterior4}>
          <Image src='./images/half meterior3.svg' width={300} height={300} />
        </div>
        <div className={styles.meterior1}>
          <Image src='./images/meteror half.svg' width={150} height={150} />
        </div>
        <motion.div className={styles.planet}
          animate={{
            y: [ 0, 20, 0 ],
            borderRadius: ["0%", "0%", "50%", "50%", "0%"]
          }}
          transition={{
            duration: 5,
            repeat: Infinity,
          }}
        >
          <Image src='./images/planet.svg' width={200} height={200} />
        </motion.div>
        <motion.div className={styles.satellite}
          animate={{
            rotate: 360,
            borderRadius: ["0%", "0%", "50%", "50%", "0%"]
          }}
          transition={{
            duration: 120,
            repeat: Infinity,
          }}          
        >
          <Image src='./images/satellite.svg' width={150} height={150} />
        </motion.div>
        <div className={styles.meterior3}>
          <Image src='./images/second half.svg' width={200} height={200} />
        </div>
        <div className={styles.astronaut}>
          <Image src='./images/manWithSpacesuit.svg' width={90} height={90} />
        </div>
        <div className={styles.small2}>
          <Image src='./images/small meterior 2.svg' width={110} height={110} />
        </div>
        <div className={styles.small1}>
          <Image src='./images/small meterior 1.svg' width={200} height={200} />
        </div>
        <div className={styles.small3}>
          <Image src='./images/small meterior 3.svg' width={110} height={110} />
        </div>
        <div className={styles.meterior2}>
          <Image src='./images/Untitled design (49) 4.svg' width={144} height={144} />
        </div>
      </div>
    </div>
  )
}
